name: Close stale issues
on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 14
          days-before-issue-close: 14
          stale-issue-message: >
            This issue has been automatically marked as stale because it has not had activity
            in a long time. If this issue is still relevant and should remain open, please reply
            with a short explanation (e.g. "Here's a screenshot of this issue on the latest version").
            Thank you for your contributions!
          close-issue-message: >
            This issue has been automatically closed because it has not had
            activity in a long time. Please feel free to reopen it or create a new issue.
